# Generated by Django 3.0.1 on 2019-12-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentals', '0002_tech'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('mobile', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('namespace', models.CharField(max_length=50)),
                ('confirmation_hash', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('href', models.CharField(max_length=200)),
                ('target_id', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
