# Generated by Django 3.0.1 on 2019-12-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentals', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='namespace',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='target_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
    ]
